apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/redis
